### PR TITLE
Week2-project PR

### PR DESCRIPTION
**Pull request by SaraChen1020**
彭彭老師好，我是陳思安，本週任務已完成再請確認:)
http://35.175.100.203:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done but your code will load the same page data multiple times if we scroll down and up quickly.

**Comment by SaraChen1020** [comment]
彭彭老師好，已調整重覆載入問題，再請您確認
http://35.175.100.203:3000/

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Comment by SaraChen1020** [comment]
謝謝彭彭老師!

**Pull request merged**
